/** Autogenerated Main.cpp. */

// ===============================| Include only the DSP files  |===============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =========================| Now we can add the rest of the codebase |=========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// =====================================| Project Factory |=====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------------
		
		registerPolyNode<project::shfiter<1>, project::shfiter<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::klp2<1>, scriptnode::wrap::illegal_poly<project::klp2<1>>>();
		registerPolyNode<project::klp<1>, scriptnode::wrap::illegal_poly<project::klp<1>>>();
		registerPolyNode<project::khp2<1>, scriptnode::wrap::illegal_poly<project::khp2<1>>>();
		registerPolyNode<project::khp<1>, scriptnode::wrap::illegal_poly<project::khp<1>>>();
		registerPolyNode<project::Comb<1>, project::Comb<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::filtest<1>, project::filtest<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::cab_networkdata>();
		registerDataNode<project::DspNetwork_networkdata>();
		registerDataNode<project::lfo_networkdata>();
		registerDataNode<project::MDel_networkdata>();
		registerDataNode<project::osctests_networkdata>();
		registerDataNode<project::tabletest_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::verb_networkdata>();
		registerDataNode<project::_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


