/** Autogenerated Main.cpp. */

// =============================| Include only the DSP files  |=============================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =======================| Now we can add the rest of the codebase |=======================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ===================================| Project Factory |===================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------
		
		registerPolyNode<project::granular<1>, project::granular<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::g<1>, project::g<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::filtest<1>, project::filtest<NUM_POLYPHONIC_VOICES>>();
		registerPolyNode<project::lfo<1>, wrap::illegal_poly<project::lfo<1>>>();
		registerPolyNode<project::table<1>, wrap::illegal_poly<project::table<1>>>();
		registerPolyNode<project::verb<1>, wrap::illegal_poly<project::verb<1>>>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::blank_networkdata>();
		registerDataNode<project::BypassTest_networkdata>();
		registerDataNode<project::cablein_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::env_networkdata>();
		registerDataNode<project::file_networkdata>();
		registerDataNode<project::filter_networkdata>();
		registerDataNode<project::gain_networkdata>();
		registerDataNode<project::gtest_networkdata>();
		registerDataNode<project::modsource_networkdata>();
		registerDataNode<project::osc_networkdata>();
		registerDataNode<project::out_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::polymod2_networkdata>();
		registerDataNode<project::polymod3_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::shaper_networkdata>();
		registerDataNode<project::track_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


