/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Comb.h"
#include "khp.h"
#include "khp2.h"
#include "klp.h"
#include "klp2.h"
#include "shfiter.h"

// Include compiled network files ------------------

#include "cab_networkdata.h"
#include "DspNetwork_networkdata.h"
#include "filtest.h"
#include "lfo_networkdata.h"
#include "MDel_networkdata.h"
#include "osctests_networkdata.h"
#include "tabletest_networkdata.h"
#include "verb_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

