/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "g.h"
#include "granular.h"

// Include compiled network files ------------------

#include "blank_networkdata.h"
#include "BypassTest_networkdata.h"
#include "cablein_networkdata.h"
#include "env_networkdata.h"
#include "file_networkdata.h"
#include "filter_networkdata.h"
#include "filtest.h"
#include "gain_networkdata.h"
#include "gtest_networkdata.h"
#include "lfo.h"
#include "modsource_networkdata.h"
#include "osc_networkdata.h"
#include "out_networkdata.h"
#include "polymod2_networkdata.h"
#include "polymod3_networkdata.h"
#include "shaper_networkdata.h"
#include "table.h"
#include "track_networkdata.h"
#include "verb.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

