/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include third party header files ----------------

#include "Comb.h"
#include "khp.h"
#include "khp2.h"
#include "klp.h"
#include "klp2.h"
#include "shfiter.h"

// Include compiled network files ------------------

#include "arrange_networkdata.h"
#include "env_networkdata.h"
#include "files.h"
#include "fx.h"
#include "HpLp.h"
#include "input_networkdata.h"
#include "Lfos_networkdata.h"
#include "lfo_networkdata.h"
#include "mix_networkdata.h"
#include "osc1_networkdata.h"
#include "osc2_networkdata.h"
#include "osc3_networkdata.h"
#include "osc4_networkdata.h"
#include "OscOut1_networkdata.h"
#include "oscshaper.h"
#include "OscTest_networkdata.h"
#include "out1_networkdata.h"
#include "send1_networkdata.h"
#include "Send2_networkdata.h"
#include "send3_networkdata.h"
#include "send4_networkdata.h"
#include "send5_networkdata.h"
#include "send6_networkdata.h"
#include "send7_networkdata.h"
#include "ShaperMod_networkdata.h"
#include "TransFX.h"
#include "VoiceOut1_networkdata.h"
#include "voice_networkdata.h"
#include "_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

