namespace project
{

struct Lfos_networkdata: public scriptnode::dll::InterpretedNetworkData
{
	String getId() const override
	{
		return "Lfos";
	}
	bool isModNode() const override
	{
		return false;
	}
	String getNetworkData() const override
	{
		return "785.nT6K8CFXNzCF.XKGbcB7Nca.O.8ZUatbwXnYD0mm6FnSJ8oOYdHSuAmrIkM1MZBhLHB6NEvS.3D.RAP+w4dvYUFG.bxOb.Yov.rZMbdV6YsXGtEy0z54IG1JtpntD1U4ewE31Jp8mSzud0P7vsN16w41JKFhakOTi5TrZOINLka0rogasf9XTcOAXdL0iEFB6gT+yNyZJSs4xkxOS0KQ6PxGV63F12oJ9TIWxSZh9YlWYDr35iiDgwDjDOf.RnFy6jZbqI4ZXHOScmkcquEaJjvNraWMpWoAbjGuZm80sFf33o.axwjaznNIRaNbpiSMnFma2t1ZL4wY1mogqxoQrrlvPb4DLAuKumECUdRrrrdL.XdbTKefC3Ug5v3D1gGXBkG0tgx.BZ5UPsvBWtXwhiJUdPo9QPWnZXPBG.wfYbjceR.AmSvJ0mO8ikkITvfYBlIUnae7yTURBqaOkuDE6QerDSvRARwPDlnpzuvYIMVKZetdsifopztBZ9Om.NKpA1bFZlQP.ABHA.F..htw1HUVJTH.PDVHVNEfP..x.HRh.PBGDfBHrvNHN4FXe6qkFrGRsNfcJ0RKVz6yn.gpsC1oLnPhPKhlfKofp.7sTtbARnPiF.r+m+qJ9VYzdeiTGWv8M10lazviNaHUupyGMZcCXCQV3osWxHDQgWEGXQRrrAPbw5Wfcf1KUkEiJU.+sJlgM6XECsDNYHjJQ+cqFzJpAHZXhQVnZBUT97PrWhDemeqDu+fk0SfpqAwFVa1+JLxyHQj4DoP7g6ak8VTE3ZCwKBaY5zgI6Nvkd3mvT3RMcI7I6zb+Ahk0EOPowl8halpp1dzfBvLhaLGymIG3sIte4STE7x.NCYj4kT5pe+aOcVeddKTshlN5OQqanFsHJldn7kZ7xBc8jimBiQotfMGAcxMw6a.IURVdC.J6sJVXGf3V8ZviDbUS3M9IIrQpe405pMXwbMvVaG.cwvpeFN3a2UmLHRLJOhNhzSFRpQvUVmR1Ee5Ty+kK+VmmIG.vVcBM3tHsNbQOpL10MtxjGO.";
	}
};
}

